server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: 'true'
      base-path: /actuator
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always

eureka:
  instance:
    instance-id: ${spring.application.name}:8081
  client:
    instance:
      preferIpAddress: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: onemore
  data:
    mongodb:
      uri: mongodb+srv://mascota:tKY4Qe7y3egpXZ62@mascotacluster.nbk3ema.mongodb.net/
      database: mascotaMongo
  mvc:
    async:
      request-timeout: 7500
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: smtp.freesmtpservers.com
    port: 25
    username: sma@mascota.com
    properties:
      mail:
        smtp:
          auth: None

mascota:
  app:
    logger: mascota-app-logger

# Ubuntu
seleniumDriverPath: /usr/bin/chromedriver

# Windows
#seleniumDriverPath: /src/main/resources/driver/chromedriver.exe